# Generated by Django 4.2.15 on 2024-08-31 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='banners')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='banners')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='banners')),
                ('imagem4', models.ImageField(blank=True, null=True, upload_to='banners')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('bv_desc', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=300)),
                ('funcao', models.CharField(max_length=60)),
                ('tags', models.CharField(max_length=40)),
                ('imagens_produto', models.ImageField(blank=True, null=True, upload_to='imagens_produtos')),
                ('data_adicionada', models.DateField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_servico', to='bond.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('bv_desc', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=300)),
                ('funcao', models.CharField(max_length=60)),
                ('tags', models.CharField(max_length=40)),
                ('imagens_produto', models.ImageField(blank=True, null=True, upload_to='imagens_produtos')),
                ('data_adicionada', models.DateField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_produto', to='bond.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('creditos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
