# Generated by Django 4.2.15 on 2024-08-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='banner',
            name='descricao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
