# Generated by Django 4.2.15 on 2025-01-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagens_produtos'),
        ),
        migrations.AlterField(
            model_name='confiabilidade',
            name='imagemDoc',
            field=models.ImageField(blank=True, null=True, upload_to='media/docs'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/users'),
        ),
    ]
