# Generated by Django 4.2.15 on 2024-08-31 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0002_rename_nome_banner_titulo_banner_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='imagem2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='imagem3',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='imagem4',
        ),
    ]
