# Generated by Django 4.2.15 on 2024-09-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0006_carrinho_produto_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='visualizacao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servico',
            name='visualizacao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
