# Generated by Django 4.2.15 on 2024-09-07 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0008_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
