# Generated by Django 4.2.15 on 2024-09-08 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0014_alter_produto_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='seller',
        ),
    ]
