# Generated by Django 4.2.15 on 2024-09-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0018_customuser_data_nas'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
