# Generated by Django 4.2.15 on 2024-09-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0021_alter_customuser_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
