# Generated by Django 4.2.15 on 2024-09-08 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bond', '0022_alter_banner_imagem1_alter_customuser_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagen',
            name='user',
        ),
        migrations.AddField(
            model_name='mensagen',
            name='user_env',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_env', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensagen',
            name='user_rec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_rec', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
