# Generated by Django 4.2.15 on 2024-09-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0023_remove_mensagen_user_mensagen_user_env_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagen',
            name='titulo',
            field=models.CharField(default='mensagem', max_length=60),
            preserve_default=False,
        ),
    ]
