# Generated by Django 4.2.15 on 2024-09-08 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bond', '0024_mensagen_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagen',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Enviada', 'Enviada'), ('Recebida', 'Recebida')], default='Pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='Mensagem_Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('mensagem', models.CharField(max_length=400)),
                ('user_env', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_env_manager', to=settings.AUTH_USER_MODEL)),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rec_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
