# Generated by Django 4.2.15 on 2024-09-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0026_servico_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem_manager',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Enviada', 'Enviada'), ('Recebida', 'Recebida')], default='Pendente', max_length=20),
        ),
    ]
