# Generated by Django 4.2.15 on 2024-09-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0027_mensagem_manager_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem_manager',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada')], default='Pendente', max_length=20),
        ),
    ]
