# Generated by Django 4.2.15 on 2024-09-13 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bond', '0028_alter_mensagem_manager_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem_manager',
            name='user_env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_env_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagen',
            name='user_env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_env', to=settings.AUTH_USER_MODEL),
        ),
    ]
