# Generated by Django 4.2.15 on 2024-10-08 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0030_alter_customuser_creditos_creditos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creditos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditosCustom', to='bond.creditos'),
        ),
    ]
