# Generated by Django 4.2.15 on 2024-10-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0036_comentario_data_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bond.customuser'),
            preserve_default=False,
        ),
    ]
