# Generated by Django 4.2.15 on 2024-10-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0037_comentario_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='imagem',
            new_name='customUser',
        ),
    ]
