# Generated by Django 4.2.15 on 2024-10-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0039_alter_customuser_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto_carrinho',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bond.produto'),
        ),
    ]
