# Generated by Django 4.2.15 on 2024-10-17 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0041_alter_produto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bond.servico'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bond.produto'),
        ),
    ]
