# Generated by Django 4.2.15 on 2024-10-23 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bond', '0043_rename_imagens_produto_servico_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('bv_desc', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=300)),
                ('funcao', models.CharField(max_length=60)),
                ('tags', models.CharField(max_length=40)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_produtos')),
                ('data_adicionada', models.DateField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('visualizacao', models.PositiveIntegerField(default=0)),
                ('avaliacao', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('servico', 'Servico'), ('produto', 'Produtp')], max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_produto', to='bond.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='servico',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='produto_carrinho',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
