# Generated by Django 4.2.15 on 2024-10-24 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0044_anuncio_remove_servico_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bond.anuncio'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='bond.anuncio'),
        ),
        migrations.AddField(
            model_name='produto_carrinho',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bond.anuncio'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bond.anuncio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(choices=[('produto', 'Produtp'), ('servico', 'Servico')], max_length=10),
        ),
    ]
