# Generated by Django 4.2.15 on 2024-11-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0046_extrato_transacao_remove_transaction_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='tipo_transacao',
            field=models.CharField(choices=[('UserforUser', 'UserforUser'), ('acr_Credito', 'acr_Credito')], default='UserforUser', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(choices=[('servico', 'Servico'), ('produto', 'Produtp')], max_length=10),
        ),
    ]
