# Generated by Django 4.2.15 on 2024-11-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0047_transacao_tipo_transacao_alter_anuncio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluida', 'Concluida'), ('Recusada', 'Recusada')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(choices=[('produto', 'Produtp'), ('servico', 'Servico')], max_length=10),
        ),
    ]
