# Generated by Django 4.2.15 on 2024-11-04 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0049_credito_pedido_remove_creditos_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carrinho',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='Carrinho_pedido', to='bond.carrinho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(choices=[('servico', 'Servico'), ('produto', 'Produtp')], max_length=10),
        ),
    ]
