# Generated by Django 4.2.15 on 2024-11-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0052_remove_pedido_produtos_pedido_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(choices=[('produto', 'Produtp'), ('servico', 'Servico')], max_length=10),
        ),
    ]
