# Generated by Django 4.2.15 on 2024-11-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0053_pedido_comprovante_alter_anuncio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='vendas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo',
            field=models.CharField(choices=[('servico', 'Servico'), ('produto', 'Produtp')], max_length=10),
        ),
    ]
